# FRAMERATE = 13
# FRAMEDUR = 1 / FRAMERATE
# GRID_SIZE = (128, 128)
# MICROSCOPE_CENTER = (GRID_SIZE[0]/2, GRID_SIZE[1]/2)
# MICROSCOPE_RADIUS = 50
# SQUARE_SIZE = 8

FRAMERATE = 13
FRAMEDUR = 1 / FRAMERATE
GRID_SIZE = (64, 64)
MICROSCOPE_CENTER = (GRID_SIZE[0]/2, GRID_SIZE[1]/2)
MICROSCOPE_RADIUS = int(GRID_SIZE[0] * 0.4)
SQUARE_SIZE = 16
