# FRAMERATE = 13
# FRAMEDUR = 1 / FRAMERATE
# GRID_SIZE = (96, 64)
# MICROSCOPE_CENTER = (GRID_SIZE[0]/2, GRID_SIZE[1]/2)
# MICROSCOPE_RADIUS = int(GRID_SIZE[0] * 0.5)
# SQUARE_SIZE = 16

FRAMERATE = 13
FRAMEDUR = 1 / FRAMERATE
GRID_SIZE = (24, 16)
MICROSCOPE_CENTER = (GRID_SIZE[0]/2, GRID_SIZE[1]/2)
MICROSCOPE_RADIUS = int(GRID_SIZE[0] * 0.5)
SQUARE_SIZE = 64
