FRAMERATE = 13
FRAMEDUR = 1 / FRAMERATE
SQUARE_SIZE = 20
GRID_SIZE = (1024 // SQUARE_SIZE, 1024 // SQUARE_SIZE)
MICROSCOPE_CENTER = (GRID_SIZE[0]/2, GRID_SIZE[1]/2)
MICROSCOPE_RADIUS = int(GRID_SIZE[0] * 0.45)
GLOBAL_PITCH_SHIFT = 0
